version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: ring.do
    volumes:
      - .:/srv/jekyll
    ports:
      - "4001:4000"
    command: >
      sh -c "bundle install && bundle exec jekyll serve --watch --drafts --host 0.0.0.0"
    stdin_open: true
    tty: true
